# app/Dockerfile
FROM python:3.9-slim

WORKDIR /app

# Копируем requirements.txt
COPY requirements.txt ./

# Устанавливаем зависимости из requirements.txt
RUN pip install -r requirements.txt

# Копируем код приложения
COPY . .

# Открываем порт
EXPOSE 5000

# Запускаем приложение
CMD ["python", "app.py"]